# Generated by Django 3.2.13 on 2022-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_details1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
